# Generated by Django 4.1.7 on 2023-02-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fee_payment',
        ),
    ]
