# Generated by Django 4.1.7 on 2023-02-21 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_cep_alter_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='days',
            new_name='day_of_week',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
