# Generated by Django 4.1.7 on 2023-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_days_booking_day_of_week_booking_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(),
        ),
    ]
