# Generated by Django 4.1.7 on 2023-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_booking_day_of_week_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.BooleanField(verbose_name='Are you ready for do the booking?'),
        ),
    ]
